@extends('layouts.admin')
@section('page_eyebrow','PLATEFORME / DEMANDE')
@section('page_title',$request->title)
@section('page_description','Dossier transactionnel et historique des transitions.')
@section('page_actions')<a class="button button--secondary" href="{{ route('admin.service-requests.index') }}"><i class="fa-solid fa-arrow-left"></i> Demandes</a>@endsection
@section('content')
@if(session('success'))<div class="admin-alert admin-alert--success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="admin-alert admin-alert--danger" role="alert">{{ $errors->first() }}</div>@endif
<div class="admin-detail-grid"><section class="admin-card"><div class="admin-card__header"><div><span class="admin-card__eyebrow">Dossier</span><h3>Participants</h3></div><span class="admin-status admin-status--{{ $request->status->value }}">{{ $request->status->value }}</span></div><dl class="admin-detail-list"><div><dt>Client</dt><dd>{{ $request->client->name ?? '—' }}</dd></div><div><dt>Professionnel</dt><dd>{{ $request->professional->user->name ?? '—' }}</dd></div><div><dt>Service</dt><dd>{{ $request->service->title ?? '—' }}</dd></div><div><dt>Adresse</dt><dd>{{ $request->address->label ?? '—' }}</dd></div><div><dt>Budget</dt><dd>{{ $request->budget_min ?? '—' }} — {{ $request->budget_max ?? '—' }} {{ $request->currency }}</dd></div><div><dt>Date souhaitée</dt><dd>{{ $request->desired_at?->format('d/m/Y H:i') ?? '—' }}</dd></div></dl><p>{{ $request->description }}</p>
@can('adminManage',$request)@if(in_array($request->status->value,['draft','requested']))<div class="admin-action-row"><form method="POST" action="{{ route('admin.service-requests.cancel',$request) }}" data-confirm="Annuler administrativement cette demande ?">@csrf<input type="hidden" name="reason" value="Décision administrative"><button class="button button--secondary">Annuler</button></form>@if($request->status->value==='requested')<form method="POST" action="{{ route('admin.service-requests.reject',$request) }}" data-confirm="Rejeter administrativement cette demande ?">@csrf<input type="hidden" name="reason" value="Décision administrative"><button class="button button--secondary">Rejeter</button></form>@endif</div>@endif@endcan
</section>
<section class="admin-card"><div class="admin-card__header"><div><span class="admin-card__eyebrow">Traçabilité</span><h3>Historique des statuts</h3></div></div><div class="admin-timeline">@forelse($request->statusHistories as $history)<article class="admin-timeline__item"><div class="admin-timeline__dot"></div><div><strong>{{ $history->from_status }} → {{ $history->to_status }}</strong><p>{{ $history->actor->name ?? 'Système' }} · {{ $history->created_at?->format('d/m/Y H:i') }}</p>@if($history->reason)<p>{{ $history->reason }}</p>@endif</div></article>@empty<p class="admin-muted">Aucun historique.</p>@endforelse</div></section></div>
@endsection