@extends('layouts.client')
@section('title','Détail du devis')
@push('head')
    @vite('resources/css/pages/client/favorites-requests-quotes.css')
@endpush
@push('scripts')
    @vite('resources/js/pages/client/favorites-requests-quotes.js')
@endpush

@section('content')
<div class="client-module"><div class="client-module__header"><div><p class="client-module__eyebrow">DEVIS #{{ $quotation->id }}</p><h1>Proposition commerciale</h1><p>{{ $quotation->serviceRequest?->service?->title }} · {{ $quotation->serviceRequest?->professional?->user?->name }}</p></div><span class="status-badge status-badge--{{ $quotation->status->value }}">{{ ucfirst($quotation->status->value) }}</span></div>
@if(session('success'))<x-alert type="success" :message="session('success')" />@endif
@if($quotation->currentOffer)<section class="client-panel client-panel--accent"><p class="client-module__eyebrow">OFFRE COURANTE</p><h2>{{ number_format((float)$quotation->currentOffer->amount,2,',',' ') }} {{ $quotation->currentOffer->currency }}</h2><p>{{ $quotation->currentOffer->description }}</p><dl class="client-definition-list"><div><dt>Durée</dt><dd>{{ $quotation->currentOffer->duration_value }} {{ $quotation->currentOffer->duration_unit->value }}</dd></div><div><dt>Valable jusqu'au</dt><dd>{{ optional($quotation->currentOffer->valid_until)->format('d/m/Y à H:i') }}</dd></div><div><dt>Conditions</dt><dd>{{ $quotation->currentOffer->conditions ?: 'Aucune condition supplémentaire.' }}</dd></div></dl></section>@endif
<section class="client-panel"><h2>Historique des offres</h2><div class="client-offer-history">@foreach($quotation->offers as $offer)<article><div><strong>Offre v{{ $offer->version }}</strong><span>{{ $offer->actor_type->value }}</span></div><strong>{{ number_format((float)$offer->amount,2,',',' ') }} {{ $offer->currency }}</strong><small>{{ optional($offer->created_at)->format('d/m/Y à H:i') }}</small></article>@endforeach</div></section>
@if($quotation->currentOffer && optional($quotation->currentOffer->valid_until)->isPast() && in_array($quotation->status->value,['sent','negotiating'],true))<div class="client-form-alert" role="status"><strong>Cette offre a expiré.</strong><p>Le professionnel devra proposer une nouvelle offre avant toute acceptation.</p></div>@endif
@if(in_array($quotation->status->value,['sent','negotiating'],true) && $quotation->currentOffer && optional($quotation->currentOffer->valid_until)->isFuture())<section class="client-panel"><h2>Votre décision</h2><div class="client-action-bar"><form method="POST" action="{{ route('client.quotes.accept',$quotation) }}">@csrf<button class="btn btn-primary" type="submit" data-confirm-submit="Confirmer l’acceptation de cette offre ?">Accepter le devis</button></form><form method="POST" action="{{ route('client.quotes.reject',$quotation) }}">@csrf<button class="btn btn-danger" type="submit" data-confirm-submit="Voulez-vous vraiment refuser ce devis ?">Refuser</button></form></div></section>
<section class="client-panel"><h2>Faire une contre-proposition</h2><form class="client-form-grid" method="POST" action="{{ route('client.quotes.counter-offer',$quotation) }}">@csrf<x-input name="amount" label="Montant" type="number" step="0.01" min="0.01" required /><x-input name="currency" label="Devise" value="{{ $quotation->currentOffer?->currency }}" maxlength="3" required /><x-input name="duration_value" label="Durée" type="number" min="1" required /><x-select name="duration_unit" label="Unité" :options="['hours'=>'Heure(s)','days'=>'Jour(s)','weeks'=>'Semaine(s)']" required /><x-input name="valid_until" label="Valable jusqu'au" type="datetime-local" required /><x-textarea class="client-form-grid__full" name="description" label="Description" rows="4" required /><x-textarea class="client-form-grid__full" name="conditions" label="Conditions" rows="3" /><div class="client-form-grid__full client-action-bar"><button class="btn btn-primary" type="submit">Envoyer la contre-proposition</button></div></form></section>@endif
<a class="btn btn-secondary" href="{{ route('client.quotes.index') }}">Retour aux devis</a></div>
@endsection