@extends('layouts.admin')
@section('page_eyebrow','PLATEFORME / DOSSIER')
@section('page_title',$professional->user->name ?? 'Professionnel')
@section('page_description',$professional->professional_title ?: 'Dossier professionnel')
@section('page_actions')<a class="button button--secondary" href="{{ route('admin.professionals.index') }}"><i class="fa-solid fa-arrow-left"></i> Professionnels</a>@endsection
@section('content')
@if(session('success'))<div class="admin-alert admin-alert--success" role="status"><i class="fa-solid fa-circle-check"></i>{{ session('success') }}</div>@endif
@if($errors->any())<div class="admin-alert admin-alert--danger" role="alert"><i class="fa-solid fa-triangle-exclamation"></i>{{ $errors->first() }}</div>@endif
<div class="admin-detail-grid">
<section class="admin-card"><div class="admin-card__header"><div><span class="admin-card__eyebrow">Identité</span><h3>{{ $professional->user->name }}</h3></div><span class="admin-status admin-status--{{ $professional->user->account_status?->value }}">{{ $professional->user->account_status?->value === 'active'?'Actif':'Suspendu' }}</span></div>
<dl class="admin-detail-list"><div><dt>E-mail</dt><dd>{{ $professional->user->email }}</dd></div><div><dt>Titre</dt><dd>{{ $professional->professional_title ?: 'Non renseigné' }}</dd></div><div><dt>E-mail vérifié</dt><dd>{{ $professional->user->email_verified_at ? 'Oui':'Non' }}</dd></div><div><dt>Rôles</dt><dd><div class="admin-chip-list">@foreach($professional->user->roles as $role)<span class="admin-chip">{{ $role->display_name }}</span>@endforeach</div></dd></div></dl>
<div class="admin-action-row">@if($professional->user->account_status?->value === 'suspended')@can('activate',$professional)<form method="POST" action="{{ route('admin.professionals.activate',$professional) }}" data-confirm="Réactiver ce compte professionnel ?">@csrf<button class="button button--primary" type="submit">Réactiver</button></form>@endcan @else @can('suspend',$professional)<form method="POST" action="{{ route('admin.professionals.suspend',$professional) }}" data-confirm="Suspendre ce compte professionnel ? Les sessions actives seront révoquées.">@csrf<button class="button button--secondary" type="submit">Suspendre</button></form>@endcan @endif</div></section>
<section class="admin-card"><div class="admin-card__header"><div><span class="admin-card__eyebrow">État professionnel</span><h3>Vérification & activité</h3></div></div><div class="admin-stat-grid"><div class="admin-stat"><span>Vérification</span><strong>{{ ['pending'=>'En attente','under_review'=>'En revue','verified'=>'Vérifié','rejected'=>'Rejeté'][$professional->verification_status?->value] ?? '—' }}</strong></div><div class="admin-stat"><span>Disponibilité</span><strong>{{ ['available'=>'Disponible','unavailable'=>'Indisponible','unknown'=>'Inconnue'][$professional->availability_status?->value] ?? '—' }}</strong></div><div class="admin-stat"><span>Note</span><strong>{{ $professional->rating_average }}/5</strong></div><div class="admin-stat"><span>Avis</span><strong>{{ $professional->reviews_count }}</strong></div><div class="admin-stat"><span>Services</span><strong>{{ $professional->services_count }}</strong></div><div class="admin-stat"><span>Demandes</span><strong>{{ $professional->service_requests_count }}</strong></div></div></section>
</div>
<section class="admin-card"><div class="admin-card__header"><div><span class="admin-card__eyebrow">Compétences</span><h3>Expertises déclarées</h3></div></div><div class="admin-chip-list admin-chip-list--large">@forelse($professional->skills as $skill)<span class="admin-chip">{{ $skill->name }} @if($skill->pivot?->years_experience)· {{ $skill->pivot->years_experience }} an{{ $skill->pivot->years_experience>1?'s':'' }}@endif</span>@empty<span class="admin-muted">Aucune compétence renseignée.</span>@endforelse</div></section>
<section class="admin-card"><div class="admin-card__header"><div><span class="admin-card__eyebrow">Workflow</span><h3>Vérification professionnelle</h3></div></div><div class="admin-action-row">
@if($professional->verification_status?->value === 'pending')@can('review',$professional)<form method="POST" action="{{ route('admin.professionals.verification.start',$professional) }}">@csrf<button class="button button--primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i> Démarrer la revue</button></form>@endcan
@elseif($professional->verification_status?->value === 'under_review')@can('verify',$professional)<button class="button button--primary" type="button" data-open-note="verify-modal"><i class="fa-solid fa-circle-check"></i> Vérifier</button>@endcan @can('reject',$professional)<button class="button button--secondary" type="button" data-open-note="reject-modal"><i class="fa-solid fa-circle-xmark"></i> Rejeter</button>@endcan
@else<span class="admin-muted">Aucune transition supplémentaire n’est autorisée pour cet état.</span>@endif
</div>
<div class="admin-timeline">@forelse($professional->verificationReviews as $review)<article class="admin-timeline__item"><div class="admin-timeline__dot"></div><div><strong>{{ $review->from_status?->value ?? '—' }} → {{ $review->to_status?->value ?? '—' }}</strong><p>{{ $review->admin?->name ?? 'Administration' }} · {{ $review->created_at?->format('d/m/Y H:i') }}</p>@if($review->reason_code)<p>Motif : {{ $review->reason_code }}</p>@endif @if($review->note)<p>{{ $review->note }}</p>@endif</div></article>@empty<p class="admin-muted">Aucun historique de vérification.</p>@endforelse</div></section>
@if($professional->verification_status?->value === 'under_review')
@can('verify',$professional)<div id="verify-modal" class="admin-modal" hidden><div class="admin-modal__panel" role="dialog" aria-modal="true" aria-labelledby="verify-title"><h3 id="verify-title">Vérifier le professionnel</h3><form method="POST" action="{{ route('admin.professionals.verification.verify',$professional) }}">@csrf<label class="admin-field"><span>Note interne</span><textarea name="note" maxlength="2000" rows="4"></textarea></label><div class="admin-action-row"><button class="button button--secondary" type="button" data-close-modal>Annuler</button><button class="button button--primary" type="submit">Confirmer</button></div></form></div></div>@endcan
@can('reject',$professional)<div id="reject-modal" class="admin-modal" hidden><div class="admin-modal__panel" role="dialog" aria-modal="true" aria-labelledby="reject-title"><h3 id="reject-title">Rejeter la vérification</h3><form method="POST" action="{{ route('admin.professionals.verification.reject',$professional) }}">@csrf<label class="admin-field"><span>Motif</span><select name="reason_code" required><option value="DOCUMENT_INVALID">Document invalide</option><option value="PROFILE_INCOMPLETE">Profil incomplet</option><option value="IDENTITY_MISMATCH">Identité non concordante</option><option value="OTHER">Autre</option></select></label><label class="admin-field"><span>Note</span><textarea name="note" maxlength="2000" rows="5"></textarea></label><div class="admin-action-row"><button class="button button--secondary" type="button" data-close-modal>Annuler</button><button class="button button--primary" type="submit">Confirmer le rejet</button></div></form></div></div>@endcan
@endif
@endsection
