@extends('layouts.admin')
@push('head')@unless(app()->environment('testing'))@vite('resources/css/pages/admin/payments.css')@endunless@endpush
@section('page_title','Paiement #'.$payment->id)@section('page_description','Dossier du paiement, de son intent et de ses transactions.')
@section('content')
<div class="admin-transaction-grid">
<section class="admin-card"><h3>Paiement</h3><div class="admin-detail-list"><div><span>Statut</span><strong>{{ $payment->status->value }}</strong></div><div><span>Montant</span><strong>{{ number_format((float)$payment->amount,2) }} {{ $payment->currency }}</strong></div><div><span>Méthode</span><strong>{{ $payment->method->value??'—' }}</strong></div><div><span>Provider</span><strong>{{ $payment->provider->value??'—' }}</strong></div><div><span>Payé le</span><strong>{{ $payment->paid_at?->format('d/m/Y H:i')??'—' }}</strong></div></div></section>
<section class="admin-card"><h3>Commande</h3><div class="admin-detail-list"><div><span>Numéro</span><strong><a href="{{ route('admin.orders.show',$payment->order) }}">{{ $payment->order?->order_number??'—' }}</a></strong></div><div><span>Client</span><strong>{{ $payment->client?->name??'—' }}</strong></div></div></section>
<section class="admin-card admin-transaction-grid" style="grid-column:1/-1"><div><h3>Transactions</h3><div class="admin-detail-list">@forelse($payment->transactions as $tx)<div><span>{{ $tx->created_at?->format('d/m/Y H:i') }}</span><strong>{{ $tx->status->value }} · {{ $tx->provider_reference??'sans référence' }}</strong></div>@empty<p>Aucune transaction.</p>@endforelse</div></div><div><h3>Intent</h3><div class="admin-detail-list"><div><span>ID</span><strong>{{ $payment->intent?->id??'—' }}</strong></div><div><span>Statut</span><strong>{{ $payment->intent?->status?->value??'—' }}</strong></div><div><span>Clé d’idempotence</span><strong>Masquée</strong></div></div></div></section>
</div>
@endsection