@extends('layouts.admin')
@push('head')@unless(app()->environment('testing'))@vite('resources/css/pages/admin/orders.css')@endunless@endpush
@section('page_title',$order->order_number)@section('page_description','Dossier transactionnel de la commande.')
@section('content')
<div class="admin-transaction-grid">
<section class="admin-card"><h3>Commande</h3><div class="admin-detail-list"><div><span>Statut</span><strong>{{ $order->status->value }}</strong></div><div><span>Total</span><strong>{{ number_format((float)$order->total,2) }} {{ $order->currency }}</strong></div><div><span>Client</span><strong>{{ $order->client?->name??'—' }}</strong></div><div><span>Professionnel</span><strong>{{ $order->professional?->user?->name??'—' }}</strong></div><div><span>Créée</span><strong>{{ $order->created_at?->format('d/m/Y H:i') }}</strong></div></div></section>
<section class="admin-card"><h3>Paiement</h3><div class="admin-detail-list">@if($order->payment)<div><span>État</span><strong>{{ $order->payment->status->value }}</strong></div><div><span>Montant</span><strong>{{ number_format((float)$order->payment->amount,2) }} {{ $order->payment->currency }}</strong></div><div><span>Payé le</span><strong>{{ $order->payment->paid_at?->format('d/m/Y H:i')??'—' }}</strong></div><div><span>Provider</span><strong>{{ $order->payment->provider??'—' }}</strong></div>@else<p>Aucun paiement.</p>@endif</div></section>
<section class="admin-card"><h3>Articles</h3><div class="admin-detail-list">@foreach($order->items as $item)<div><span>{{ $item->service_title }} × {{ $item->quantity }}</span><strong>{{ number_format((float)$item->subtotal,2) }} {{ $item->currency }}</strong></div>@endforeach</div></section>
<section class="admin-card"><h3>Historique</h3><div class="admin-detail-list">@foreach($order->statusHistories as $history)<div><span>{{ $history->created_at?->format('d/m/Y H:i') }}</span><strong>{{ $history->from_status?->value??'—' }} → {{ $history->to_status->value }}</strong></div>@endforeach</div></section>
</div>
@endsection