@extends('layouts.client')
@section('title','Commande')
@section('content')
@push('head')@vite('resources/css/pages/client/orders-payments.css')@endpush
<div class="client-module">
<div class="client-module__header"><div><p class="client-module__eyebrow">COMMANDE {{ $order->order_number ?? '#'.$order->id }}</p><h1>{{ $order->items->first()?->service_title ?? 'Commande' }}</h1><p>{{ $order->professional?->user?->name }} · {{ $order->professional?->professional_title }}</p></div><span class="status-badge status-badge--{{ $order->status->value }}">{{ ucfirst(str_replace('_',' ',$order->status->value)) }}</span></div>
<div class="client-detail-grid"><section class="client-panel"><h2>Résumé</h2><dl class="client-definition-list"><div><dt>Montant</dt><dd><strong>{{ number_format((float)$order->total,2,',',' ') }} {{ $order->currency }}</strong></dd></div><div><dt>Créée le</dt><dd>{{ optional($order->created_at)->format('d/m/Y à H:i') }}</dd></div><div><dt>Acceptée le</dt><dd>{{ optional($order->accepted_at)->format('d/m/Y à H:i') ?: '—' }}</dd></div><div><dt>Confirmée le</dt><dd>{{ optional($order->confirmed_at)->format('d/m/Y à H:i') ?: '—' }}</dd></div></dl></section>
<section class="client-panel"><h2>Adresse d’exécution</h2>@if($order->addressSnapshot)<p>{{ $order->addressSnapshot->recipient_name }}</p><p>{{ $order->addressSnapshot->address_line_1 }}{{ $order->addressSnapshot->address_line_2 ? ', '.$order->addressSnapshot->address_line_2 : '' }}</p><p>{{ $order->addressSnapshot->neighborhood }}, {{ $order->addressSnapshot->commune }}</p><p>{{ $order->addressSnapshot->city }}, {{ $order->addressSnapshot->province }}</p>@else<p>Adresse non disponible.</p>@endif</section></div>
<section class="client-panel"><h2>Service</h2>@foreach($order->items as $item)<article class="order-item"><strong>{{ $item->service_title }}</strong><p>{{ $item->service_description }}</p><span>{{ number_format((float)$item->unit_price,2,',',' ') }} {{ $item->currency }} · Quantité {{ $item->quantity }}</span></article>@endforeach</section>
<section class="client-panel"><h2>Suivi</h2><ol class="client-timeline">@foreach($order->statusHistories as $history)<li><strong>{{ ucfirst(str_replace('_',' ',data_get($history->to_status,'value',$history->to_status))) }}</strong><span>{{ optional($history->created_at)->format('d/m/Y à H:i') }}</span>@if($history->reason)<p>{{ $history->reason }}</p>@endif</li>@endforeach</ol></section>
<section class="client-panel"><h2>Paiement</h2>@if($order->payment)<div class="payment-summary"><strong>{{ ucfirst($order->payment->status->value) }}</strong><span>{{ number_format((float)$order->payment->amount,2,',',' ') }} {{ $order->payment->currency }}</span></div><p>Méthode : {{ $order->payment->method->value ?? '—' }} · Fournisseur : {{ $order->payment->provider->value ?? '—' }}</p><a class="btn btn-secondary" href="{{ route('client.payments.show',$order->payment) }}">Voir le paiement</a>@elseif($order->status->value==='pending_payment')<a class="btn btn-primary" href="{{ route('client.orders.payment',$order) }}">Payer cette commande</a>@else<p>Aucun paiement enregistré.</p>@endif</section>
<div class="client-action-bar"><a class="btn btn-secondary" href="{{ route('client.orders.index') }}">Retour</a></div></div>
@endsection